# Project 2, scraping from steam sales

This project reads the data from the first 5 pages of steam sales, and parses through it to get info on each game title. It then generates and pushes this data into a dataFrame. This dataFrame is converted to a CSV for easier digestion on the executive side of things.

## Imports

In [17]:
import bs4 #beautifulsoup 4
from urllib.request import urlopen as uReq #url open module
from bs4 import BeautifulSoup as soup #beautifulsoup module
import pandas as pd
import numpy as np
import re # regex
import os
from datetime import datetime

## Read all the web pages

In [19]:
base_url = "https://store.steampowered.com/search/?specials=1&page="

# Download all 5 pages we want to scrape and dump them to a variable
uClient1 = uReq(base_url + "1")
page_html_1 = uClient1.read()
uClient2 = uReq(base_url + "2")
page_html_2 = uClient2.read()
uClient3 = uReq(base_url + "3")
page_html_3 = uClient3.read()
uClient4 = uReq(base_url + "4")
page_html_4 = uClient4.read()
uClient5 = uReq(base_url + "5")
page_html_5 = uClient5.read()
uClient1.close()
uClient2.close()
uClient3.close()
uClient4.close()
uClient5.close()

## Convert each page to soup and pick out each game

container will contain each game as it's own component

In [20]:
# Make soup out of each page
page_1 = soup(page_html_1)
page_2 = soup(page_html_2)
page_3 = soup(page_html_3)
page_4 = soup(page_html_4)
page_5 = soup(page_html_5)

# Combined all the data from each page into one container
container = page_1.find_all('a', class_="search_result_row ds_collapse_flag")
container += page_2.find_all('a', class_="search_result_row ds_collapse_flag")
container += page_3.find_all('a', class_="search_result_row ds_collapse_flag")
container += page_4.find_all('a', class_="search_result_row ds_collapse_flag")
container += page_5.find_all('a', class_="search_result_row ds_collapse_flag")

# Functions for parsing data

All functions in this section are designed for this specific instance of scraping the item in the discounted steam sales. Each function also primarily makes use of the base item, whcih we get from the soup container.

## Parse ratings into relevant formats

***See bottom of page for a small description of possible ratings***

rating_text_to_int will take convert a steam rating text, such as very positive, and convert it to an int

rating_count takes in a string and returns the 4th value when the string is split. In this application this works out to be the total ratings a game has.

parse_ratings makes splits an item into the correct formats for the 2 above functions and is the "main" function handling the ratings for the item.

parse_ratings information:
* rating contains a number from 1-9 based on how the game is rated
* rate_count is the number of ratings the item has in total
* Both values are 0 if the game has no rating

In [43]:
# Convert a specific text to int
def rating_text_to_int(text):
    if (text == "overwhelmingly positive"):
        return 9
    elif(text == "very positive"):
        return 8
    elif(text == "positive"):
        return 7
    elif(text == "mostly positive"):
        return 6
    elif(text == "mixed"):
        return 5
    elif(text == "mostly negative"):
        return 4
    elif(text == "negative"):
        return 3
    elif(text == "very negative"):
        return 2
    elif(text == "overwhelmingly negative"):
        return 1
    else:
        return 0

# Grab the count from an item
def rating_count(item):
    list = []
    for i in item.split():
        list.append(i)
    number = list[3].replace(',', '')
    number = int(number)
    # number is the number of ratings an item has in total
    return number

# Converts a text in a span to a rating as text and the count of ratings
def parse_ratings(item):
    # We find the review section in the item
    span = item.find('span', class_="search_review_summary")
    # Pick out rating from the tooltip (very positive etc.)
    try:
        content = span['data-tooltip-html']
        split = content.split('<br>')
        rating = rating_text_to_int(split[0].lower())
        rate_count = rating_count(split[1])
    except TypeError:
        rating = '0'
        rate_count = '0'
    return rating, rate_count

## Get the discounted price

The string in the item has a format which lets us split by the € and simply replace the unwanted values to get the correct price.

In [22]:
def parse_sale_price(item):
    text = item.find('div', class_="col search_price discounted responsive_secondrow").text
    price = text.split('€')[1].replace('\n', '')
    return price

## Get the discount percent from an item

We convert the percent to an int after we have replaced all unnecessary values in the string.

In [23]:
def parse_sale_percentage(item):
    text = item.find('div', class_="col search_discount responsive_secondrow").text
    text = text.replace('\n', '').replace('%', '')
    # We return the discount % as a negative int ie. -67
    return int(text)

## Get the year from an item

The year can be found in the last 4 letters of the string.

In [24]:
def parse_year(item):
    text = item.find('div', class_="col search_released responsive_secondrow").text
    return text[-4:]

## Define our pandas dataFrame

We define an empty dataFrame which we use to store our parsed data, the data has 11 columns.

In [44]:
column_names = ['Name', 'Rating', 'Rating_Count', 'Discount', 'Discount_price', 'Retail_price', 'Release_year', 'Win', 'Linux', 'Mac', 'Time']
df = pd.DataFrame(columns=column_names)
df.head()

Empty DataFrame
Columns: [Name, Rating, Rating_Count, Discount, Discount_price, Retail_price, Release_year, Win, Linux, Mac, Time]
Index: []

## Convert dataFrame types to what they should be

Many of our columns will contain integers so we already set them to be that data type

In [45]:
df.Rating = df.Rating.astype(int)
df.Rating_Count = df.Rating_Count.astype(int)
df.Discount = df.Discount.astype(int)
df.Win = df.Win.astype(int)
df.Linux = df.Linux.astype(int)
df.Mac = df.Mac.astype(int)
df.dtypes

Name              object
Rating             int32
Rating_Count       int32
Discount           int32
Discount_price    object
Retail_price      object
Release_year      object
Win                int32
Linux              int32
Mac                int32
Time              object
dtype: object

# The actual application

The application is a simple loop through each item in the container. The item is an html a tag, and contains all relevant data that we want to pick out, except for the time which we generate ourselves.

The time is separated from the loop since we want the time to be the same for each row in the dataFrame when the items were scraped at the same time. It makes for more accurate grouping/sorting when analysing the data.

## Loop through each item and append it to the dataFrame

We loop through each item and make use of the functions we defined above to get the values we want out of the item.

In [46]:
# Time is defined separately to have the same time for each item per scrape
time = datetime.now()
i = 0
for item in container:
    # Parse name
    name = item.find('span', class_="title").text
    # Parse rating & review count
    rating, rate_count = parse_ratings(item)
    # Sale %
    print(rating, rate_count)
    sale_percentage = parse_sale_percentage(item)
    # Sale price
    sale_price = parse_sale_price(item)
    # Ordinary price
    ordinary_price = item.find('strike').text.replace('€', '')
    # Release year
    release_year = parse_year(item)
    # Win
    win = 1 if bool(item.find_all('span', class_="platform_img win")) else 0
    # Linux
    linux = 1 if bool(item.find_all('span', class_="platform_img linux")) else 0
    # Mac
    mac = 1 if bool(item.find_all('span', class_="platform_img mac")) else 0
    # Time
    df.loc[i] = name, rating, rate_count, sale_percentage, sale_price, ordinary_price, release_year, win, linux, mac, time
    i += 1

8 20700
8 61835
8 37574
6 39023
8 41675
6 20649
8 65909
8 89827
8 39778
5 43173
6 24282
6 22456
8 29032
6 27583
5 9633
6 4042
8 44019
6 5685
8 96186
5 49706
6 8065
8 1703
8 35248
8 45315
5 4243
8 103
5 2228
6 1352
8 202
8 63073
7 41
6 1176
8 2127
5 171492
9 8648
8 167174
6 1376
8 6139
8 30243
6 1931
6 2251
8 30035
8 5003
8 158
6 41183
6 3504
8 5191
6 29566
8 4057
6 9472
5 5542
8 6481
8 8470
9 2583
8 5653
5 3509
6 1463
8 15396
6 4721
8 9955
6 3228
8 51775
8 25106
5 8189
6 4896
8 40732
8 41798
9 40473
6 258
8 1420
8 555
8 1721
6 2570
8 16389
8 5285
9 744
8 93368
8 5989
9 11209
8 1347
9 4961
6 2283
8 1995
8 1963
8 5565
8 43211
8 11570
5 172
8 7227
8 11302
8 6463
5 18587
5 2244
5 805
5 183
8 14871
8 2756
6 5102
6 61
8 12944
5 220
7 16
5 297
8 7165
8 748
8 576
8 3716
0 0
6 630
6 356
9 37503
8 12567
8 16829
6 1815
5 448
8 4320
8 42921
6 3385
8 5452
6 3438
8 3360
8 146
6 2365
6 4538
8 4258

## Describe the dataFrame we have just filled

This section just gives a quick insight into how the dataFrame we just generated looks with data in it.

In [28]:
df.head()

,Name,Rating,Rating_Count,Discount,Discount_price,Retail_price,Release_year,Win,Linux,Mac,Time
0,Total War: WARHAMMER II,8,20700,-66,"20,39","59,99",2017,1,1,1,2019-10-20 15:03:47.039044
1,Cities: Skylines,8,61835,-75,"6,99","27,99",2015,1,1,1,2019-10-20 15:03:47.039044
2,Hearts of Iron IV,8,37574,-60,"15,99","39,99",2016,1,1,1,2019-10-20 15:03:47.039044
3,Stellaris,6,39023,-75,"9,99","39,99",2016,1,1,1,2019-10-20 15:03:47.039044
4,Hearts of Iron IV: Mobilization Pack,8,41675,-56,"46,66","104,95",,1,1,1,2019-10-20 15:03:47.039044

In [29]:
df.describe

<bound method NDFrame.describe of                                                   Name  Rating  Rating_Count  \
0                              Total War: WARHAMMER II       8         20700
1                                     Cities: Skylines       8         61835
2                                    Hearts of Iron IV       8         37574
3                                            Stellaris       6         39023
4                 Hearts of Iron IV: Mobilization Pack       8         41675
5                         theHunter: Call of the Wild™       6         20649
6                          Cities: Skylines Collection       8         65909
7                                               Arma 3       8         89827
8                                Europa Universalis IV       8         39778
9                         Sid Meier’s Civilization® VI       5         43173
10                                Total War: WARHAMMER       6         24282
11         theHunter: Call of the Wild™ - 2019 Edition       6         22456
12                           Assassin's Creed® Odyssey       8         29032
13                             Warhammer: Vermintide 2       6         27583
14                                     Imperator: Rome       5          9633
15                                      Hell Let Loose       6          4042
16                 Crusader Kings II: Royal Collection       8         44019
17                                      Surviving Mars       6          5685
18                             Arma 3 Ultimate Edition       8         96186
19      Sid Meier's Civilization VI : Platinum Edition       5         49706
20                                          BATTLETECH       6          8065
21                                POSTAL 4: No Regerts       8          1703
22                           Assassin's Creed® Origins       8         35248
23              Crusader Kings II: Imperial Collection       8         45315
24                           Stellaris: Ascension Pack       5          4243
25                                 Little Big Workshop       8           103
26                                      DiRT Rally 2.0       5          2228
27           Warhammer 40,000: Gladius - Relics of War       6          1352
28                                           Autonauts       8           202
29                Cities: Skylines - New Player Bundle       8         63073
..                                                 ...     ...           ...
77                                  Universe Sandbox ²       8          5989
78                                     My Friend Pedro       9         11209
79                             Gensokyo Night Festival       8          1347
80                                  Touhou Luna Nights       9          4961
81                                         Worms W.M.D       6          2283
82                                 GRIP: Combat Racing       8          1995
83             Shadowrun: Hong Kong - Extended Edition       8          1963
84                                        For The King       8          5565
85                Europa Universalis IV: Empire Bundle       8         43211
86                                   My Time At Portia       8         11570
87                      EARTH DEFENSE FORCE: IRON RAIN       5           172
88                                   Shadowrun Returns       8          7227
89                   Warhammer: End Times - Vermintide       8         11302
90                                          Overcooked       8          6463
91                             Assassin's Creed® Unity       5         18587
92                                Warhammer: Chaosbane       5          2244
93                          DYNASTY WARRIORS 8 Empires       5           805
94   Europa Universalis IV: Conquest of Paradise Co...       5           183
95                                    Worms Collection       8         14871
96                                         SUPERHOT VR       8          2756
97                       Age of Wonders III Collection       6          5102
98                               All Characters Bundle       6            61
99                            Overcooked! 1 & 2 Bundle       8         12944
100                             Frostpunk: Season Pass       5           220
101                                 NEKO-NIN exHeart 3       7            16
102            Warhammer 40,000: Inquisitor - Prophecy       5           297
103                      Assassin’s Creed® Brotherhood       8          7165
104                                      Yuppie Psycho       8           748
105                         SpellForce 3: Soul Harvest       8           576
106                                      Rise to Ruins       8          3716

     Discount Discount_price Retail_price Release_year  Win  Linux  Mac  \
0         -66          20,39        59,99         2017    1      1    1
1         -75           6,99        27,99         2015    1      1    1
2         -60          15,99        39,99         2016    1      1    1
3         -75           9,99        39,99         2016    1      1    1
4         -56          46,66       104,95                 1      1    1
5         -40          11,99        19,99         2017    1      0    0
6         -56          74,73       168,83                 1      1    1
7         -66           9,51        27,99         2013    1      0    0
8         -75           9,99        39,99         2013    1      1    1
9         -70          17,99        59,99         2016    1      1    1
10        -75          14,99        59,99         2016    1      1    1
11        -43          29,39        51,93                 1      0    0
12        -50          29,99        59,99         2018    1      0    0
13        -75           6,99        27,99         2018    1      0    0
14        -33          26,79        39,99         2019    1      1    1
15        -20          23,99        29,99         2019    1      0    0
16        -55          82,20       182,85                 1      1    1
17        -66          10,19        29,99         2018    1      1    1
18        -68          39,36       124,40                 1      0    0
19        -72          47,75       167,91                 1      1    1
20        -66          13,59        39,99         2018    1      1    1
21        -10          15,11        16,79         2019    1      0    0
22        -60          23,99        59,99         2017    1      0    0
23        -59         129,76       313,36                 1      1    1
24        -54          39,49        85,93                 1      1    1
25        -10          17,99        19,99         2019    1      0    1
26        -60          21,99        54,99         2019    1      0    0
27        -50          16,99        33,99         2018    1      1    0
28        -20          15,99        19,99         2019    1      0    0
29        -66          20,66        59,96                 1      1    1
..        ...            ...          ...          ...  ...    ...  ...
77        -33          14,06        20,99         2015    1      1    1
78        -30          11,75        16,79         2019    1      0    0
79        -10           9,71        10,79         2019    1      0    0
80        -25          11,24        14,99         2019    1      0    0
81        -75           7,49        29,99         2016    1      1    1
82        -50          14,99        29,99         2018    1      0    0
83        -75           4,99        19,99         2015    1      1    1
84        -50           9,99        19,99         2018    1      1    1
85        -59         105,60       254,85                 1      1    1
86        -25          22,49        29,99         2019    1      0    0
87        -20          39,99        49,99         2019    1      0    0
88        -75           3,74        14,99         2013    1      1    1
89        -75           6,99        27,99         2015    1      0    0
90        -75           3,99        15,99         2016    1      0    0
91        -70           8,99        29,99         2014    1      0    0
92        -50          24,99        49,99         2019    1      0    0
93        -75          12,49        49,99         2015    1      0    0
94        -55          10,42        22,95                 1      1    1
95        -82          38,30       209,78                 1      0    0
96        -33          15,40        22,99         2017    1      0    0
97        -65          24,26        68,96                 1      1    1
98        -63          13,17        35,42                 1      0    1
99        -59          16,--        38,98                 1      0    0
100       -30          23,77        33,97                 1      0    0
101       -10           7,37         8,19         2019    1      0    0
102       -25          18,74        24,99         2019    1      0    0
103       -66           5,09        14,99         2011    1      0    0
104       -25          12,49        16,66         2019    1      1    1
105       -33          16,74        24,99         2019    1      0    0
106       -30           8,74        12,49         2019    1      1    1

                          Time
0   2019-10-20 15:03:47.039044
1   2019-10-20 15:03:47.039044
2   2019-10-20 15:03:47.039044
3   2019-10-20 15:03:47.039044
4   2019-10-20 15:03:47.039044
5   2019-10-20 15:03:47.039044
6   2019-10-20 15:03:47.039044
7   2019-10-20 15:03:47.039044
8   2019-10-20 15:03:47.039044
9   2019-10-20 15:03:47.039044
10  2019-10-20 15:03:47.039044
11  2019-10-20 15:03:47.039044
12  2019-10-20 15:03:47.039044
13  2019-10-20 15:03:47.039044
14  2019-10-20 15:03:47.039044
15  2019-10-20 15:03:47.039044
16  2019-10-20 15:03:47.039044
17  2019-10-20 15:03:47.039044
18  2019-10-20 15:03:47.039044
19  2019-10-20 15:03:47.039044
20  2019-10-20 15:03:47.039044
21  2019-10-20 15:03:47.039044
22  2019-10-20 15:03:47.039044
23  2019-10-20 15:03:47.039044
24  2019-10-20 15:03:47.039044
25  2019-10-20 15:03:47.039044
26  2019-10-20 15:03:47.039044
27  2019-10-20 15:03:47.039044
28  2019-10-20 15:03:47.039044
29  2019-10-20 15:03:47.039044
..                         ...
77  2019-10-20 15:03:47.039044
78  2019-10-20 15:03:47.039044
79  2019-10-20 15:03:47.039044
80  2019-10-20 15:03:47.039044
81  2019-10-20 15:03:47.039044
82  2019-10-20 15:03:47.039044
83  2019-10-20 15:03:47.039044
84  2019-10-20 15:03:47.039044
85  2019-10-20 15:03:47.039044
86  2019-10-20 15:03:47.039044
87  2019-10-20 15:03:47.039044
88  2019-10-20 15:03:47.039044
89  2019-10-20 15:03:47.039044
90  2019-10-20 15:03:47.039044
91  2019-10-20 15:03:47.039044
92  2019-10-20 15:03:47.039044
93  2019-10-20 15:03:47.039044
94  2019-10-20 15:03:47.039044
95  2019-10-20 15:03:47.039044
96  2019-10-20 15:03:47.039044
97  2019-10-20 15:03:47.039044
98  2019-10-20 15:03:47.039044
99  2019-10-20 15:03:47.039044
100 2019-10-20 15:03:47.039044
101 2019-10-20 15:03:47.039044
102 2019-10-20 15:03:47.039044
103 2019-10-20 15:03:47.039044
104 2019-10-20 15:03:47.039044
105 2019-10-20 15:03:47.039044
106 2019-10-20 15:03:47.039044

[107 rows x 11 columns]>

## Save the dataFrame to a csv file

The file name is discounts and it will be saved in the same directory as the script. If it has to create the file it will include the headers but if the file already exists it will simply append the new data to the existing file.

In [47]:
file_name = 'discounts.csv'
if (os.path.exists('discounts.csv')):
    df.to_csv(file_name, mode='a', header=False, index=False)
else:
    df.to_csv(file_name, index=False)

## Rating formats on steam

There are 10 possibilities for ratings on stea

overwhelmingly positive

very positive

positive

mostly positive

mixed

mostly negative

negative

very negative

overwhelmingly negative

no rating